version: '3.4'

services:
  guneleme:
    image: missingno/guneleme
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000 --noreload
    restart: always

  qqbot:
    image: missingno/qqbot
    volumes:
      - .:/app
      - ./qqbot/ss.json:/etc/ss.json
    working_dir: /app/qqbot
    command: python run.py
    restart: always

