# Generated by Django 2.1.1 on 2018-09-24 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('qq', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('is_lamb', models.BooleanField()),
                ('openid', models.CharField(max_length=32, null=True)),
                ('sign', models.CharField(max_length=32, null=True)),
                ('cookies', models.TextField(null=True)),
                ('last_lucky_time', models.DateTimeField(default=datetime.datetime(2018, 9, 24, 14, 43, 24, 947959))),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('sn', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('lucky_number', models.IntegerField()),
                ('current_count', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('lamb_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lamb', to='app.Account')),
                ('lucky_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lucky', to='app.Account')),
            ],
        ),
    ]
