# Generated by Django 2.1.1 on 2018-09-25 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 12, 36, 45, 986756)),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_lucky_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 12, 36, 45, 985755)),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='lamb_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lamb', to='app.Account'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='lucky_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lucky', to='app.Account'),
        ),
    ]
