# Generated by Django 2.1.1 on 2018-09-25 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180925_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='temp_lamb_until',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 17, 53, 3, 627725)),
        ),
        migrations.AlterField(
            model_name='account',
            name='cookies',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_lucky_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 17, 53, 3, 627725)),
        ),
        migrations.AlterField(
            model_name='account',
            name='openid',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='sign',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 17, 53, 3, 628724)),
        ),
    ]
