# Generated by Django 2.1.1 on 2018-09-26 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180925_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='time',
        ),
        migrations.AddField(
            model_name='coupon',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 12, 25, 54, 5453)),
        ),
        migrations.AddField(
            model_name='coupon',
            name='pick_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_lucky_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 12, 25, 54, 4454)),
        ),
        migrations.AlterField(
            model_name='account',
            name='temp_lamb_until',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 12, 25, 54, 4454)),
        ),
    ]
